/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings apps/edge/worker-configuration.d.ts` (hash: d808894cd7dc5700ea724dab2e0e5384)
interface __BaseEnv_CloudflareBindings {
	BOARD_SNAPSHOTS: R2Bucket;
	WORKER_VERSION: WorkerVersionMetadata;
	ASSETS: Fetcher;
	APP_HOSTNAME: "localhost" | "cloudflare-collab-canvas-staging.spacescale.workers.dev" | "spacescale.net";
	BOARD_CREATION_ENABLED: "true";
	TURNSTILE_SITE_KEY?: "1x00000000000000000000AA";
	TURNSTILE_ENABLED: "false" | "true";
	ENVIRONMENT: "development" | "staging" | "production";
	SESSION_SIGNING_KEY_CURRENT: string;
	SESSION_SIGNING_KEY_PREVIOUS: string;
	TURNSTILE_SECRET_KEY: string;
	BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/gateway");
		durableNamespaces: "BoardRoom";
	}
	interface DevelopmentEnv {
		BOARD_SNAPSHOTS: R2Bucket;
		WORKER_VERSION: WorkerVersionMetadata;
		ASSETS: Fetcher;
		APP_HOSTNAME: "localhost";
		BOARD_CREATION_ENABLED: "true";
		TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
		TURNSTILE_ENABLED: "false";
		ENVIRONMENT: "development";
		SESSION_SIGNING_KEY_CURRENT: string;
		SESSION_SIGNING_KEY_PREVIOUS: string;
		TURNSTILE_SECRET_KEY: string;
		BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
	}
	interface StagingEnv {
		BOARD_SNAPSHOTS: R2Bucket;
		WORKER_VERSION: WorkerVersionMetadata;
		ASSETS: Fetcher;
		APP_HOSTNAME: "cloudflare-collab-canvas-staging.spacescale.workers.dev";
		BOARD_CREATION_ENABLED: "true";
		TURNSTILE_ENABLED: "true";
		ENVIRONMENT: "staging";
		SESSION_SIGNING_KEY_CURRENT: string;
		SESSION_SIGNING_KEY_PREVIOUS: string;
		TURNSTILE_SECRET_KEY: string;
		BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_HOSTNAME" | "BOARD_CREATION_ENABLED" | "TURNSTILE_SITE_KEY" | "TURNSTILE_ENABLED" | "ENVIRONMENT" | "SESSION_SIGNING_KEY_CURRENT" | "SESSION_SIGNING_KEY_PREVIOUS" | "TURNSTILE_SECRET_KEY">> {}
}
