/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --env-interface=CloudflareBindings apps/edge/worker-configuration.d.ts` (hash: 544e91f050ffc882da11a79b915da9b4)
interface __BaseEnv_CloudflareBindings {
	BOARD_SNAPSHOTS: R2Bucket;
	BOARD_ASSETS: R2Bucket;
	WORKER_VERSION: WorkerVersionMetadata;
	ASSETS: Fetcher;
	APP_HOSTNAME: "localhost" | "staging-cloud-collab.spacescale.net" | "spacescale.net";
	BOARD_CREATION_ENABLED: "true";
	ALLOWED_ORIGINS?: "http://localhost,http://localhost:4173,http://localhost:5173,https://127.0.0.1:8787";
	TURNSTILE_SITE_KEY?: "1x00000000000000000000AA";
	TURNSTILE_ENABLED: "false" | "true";
	ENVIRONMENT: "development" | "staging" | "production";
	SESSION_SIGNING_KEY_CURRENT: string;
	SESSION_SIGNING_KEY_PREVIOUS: string;
	CLASSROOM_INTEGRATION_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/gateway");
		durableNamespaces: "BoardRoom";
	}
	interface DevelopmentEnv {
		BOARD_SNAPSHOTS: R2Bucket;
		BOARD_ASSETS: R2Bucket;
		WORKER_VERSION: WorkerVersionMetadata;
		ASSETS: Fetcher;
		APP_HOSTNAME: "localhost";
		BOARD_CREATION_ENABLED: "true";
		ALLOWED_ORIGINS: "http://localhost,http://localhost:4173,http://localhost:5173,https://127.0.0.1:8787";
		TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
		TURNSTILE_ENABLED: "false";
		ENVIRONMENT: "development";
		SESSION_SIGNING_KEY_CURRENT: string;
		SESSION_SIGNING_KEY_PREVIOUS: string;
		CLASSROOM_INTEGRATION_KEY: string;
		TURNSTILE_SECRET_KEY: string;
		BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
	}
	interface StagingEnv {
		BOARD_SNAPSHOTS: R2Bucket;
		BOARD_ASSETS: R2Bucket;
		WORKER_VERSION: WorkerVersionMetadata;
		ASSETS: Fetcher;
		APP_HOSTNAME: "staging-cloud-collab.spacescale.net";
		BOARD_CREATION_ENABLED: "true";
		TURNSTILE_ENABLED: "false";
		ENVIRONMENT: "staging";
		SESSION_SIGNING_KEY_CURRENT: string;
		SESSION_SIGNING_KEY_PREVIOUS: string;
		CLASSROOM_INTEGRATION_KEY: string;
		TURNSTILE_SECRET_KEY: string;
		BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_HOSTNAME" | "BOARD_CREATION_ENABLED" | "ALLOWED_ORIGINS" | "TURNSTILE_SITE_KEY" | "TURNSTILE_ENABLED" | "ENVIRONMENT" | "SESSION_SIGNING_KEY_CURRENT" | "SESSION_SIGNING_KEY_PREVIOUS" | "CLASSROOM_INTEGRATION_KEY" | "TURNSTILE_SECRET_KEY">> {}
}
